# define INST_OUTPUT prior to sourcing the code

[[ -z "$INST_OUTPUT" ]] && INST_OUTPUT='./inspect'
mkdir -p $INST_OUTPUT

export INST_ENV="$INST_OUTPUT/environment_data"
touch $INST_ENV
export INST_LOG="$INST_OUTPUT/abcde.log"
touch $INST_LOG

# YMMV -- these are bits of the environment I'm normally not concerned with
UNRELATED='^(?:unrelated|pull_func|__vsc|vscode|git_|diff|inst_|gnome|xdg|xmod|ssh|session|ret|qt|wd|ps4|path|suer|uid|termopt|oldpwd|mem|ls_co|logname|im_hostname|hist|gtk|gpg|gdm|euid|dbus|colu|color|bash|user|ps1|lang|display|host|group|home|mailc|ppid|ps2|opt|vte|line|dir|im_c|systemd|pwd|wayland|xauth|term|shello|desktop|ls_opt).*'

INST_DIFF=diff
INST_DIFF_OPTIONS="-N -C 1"

# This will become a separate config file, specific to the file being examined.
# or perhaps command line funtions in the setup.
[[ -z "$PULL_FUNC_FILE" ]] && PULL_FUNC_FILE='/home/paul/git/abcde/abcde'
PULL_FUNC_NODECORATE='vecho|vvecho|log' # functions not to decorate.
PULL_FUNC_VERBOSE=1